"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-de6w-01ivn!)wo^zz9hefre**))6g$luex^%u_g7mnx)4z0qe_"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Thêm news vào trong danh sách ứng dụng của hệ thống --> active ứng dụng
    "news.apps.NewsConfig",
    # Thư viện dùng để thay đổi chức năng ô nhập văn bản từ loại thường sang loại nhập HTML
    "tinymce",
    # Thư viện giúp xóa file hình ảnh cũ sau khi update hình ảnh mới
    "django_cleanup.apps.CleanupConfig",
    # Thư viện dùng để hiển thị dấu phẩy phân biệt phần nghìn, trắm, đơn vị ...
    "django.contrib.humanize"

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Đăng ký hàm lấy dữ liệu category
                # Hàm này sẽ được tự động chạy mỗi khi người dùng truy cập vào page
                "news.my_context.items_category_sidebar_menu",
                "news.my_context.items_feed_sidebar_menu",
                "news.my_context.items_article_sidebar_recent",
                "news.my_context.items_article_footer_random",
                "news.my_context.items_article_header_trending",
                "news.my_context.items_price_sidebar_coin",
                "news.my_context.items_price_sidebar_gold"
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'news',
        'USER': 'root',
        'PASSWORD': '123456789',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Đường dẫn để truy cập trên trình duyệt
# --> chỉ cho phần hiển thị, khi thay đổi vị trí/ đổi têm file static sẽ ko ảnh hưởng (không cần đổi tên lại)
STATIC_URL = "static/"

# Vị trí thư mục lưu các file static --> nếu thay đổi tên thư mục hoặc vị trí thư mục thì phải update ở đây
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# Đường dẫn để truy cập vào trình duyệt
MEDIA_URL = "/media/"

# Vị trí thư mục lưu file media (ảnh) khi upload --> nếu thay đổi vị trí lưu thì phải sửa
MEDIA_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
