# Generated by Django 4.2.5 on 2023-10-14 15:49

from django.db import migrations, models
import shop.custom_field


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_homepage", shop.custom_field.CustomBooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Category",
            },
        ),
    ]
